import Head from "next/head";

export default function Layout({title, children}) {
    return (
        <>
            <Head>
                <title>{title ? `${title} - Evermos` : 'Evermos'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container">
                <header className="header">
                    <h2>Evermos</h2>
                </header>
                <main className="main">
                    {children}
                </main>
                <footer className="footer">
                    Evermos 2022
                </footer>
            </div>
        </>
    )
}